POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Nota de contenido",
  "important": true
}

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/4

###
DELETE http://localhost:3001/api/notes/4
